### ISSUE TITLE
i cant found player with only id or not full name

### ISSUE THREAD

**Issue by rodopoulos1** [exkludera/cs2-force-say#1]
![image](https://github.com/user-attachments/assets/56af777c-e3c6-4a27-917c-2d0a64456b6e)
Look i cant do with ID 
and i cant do with not full name 
![image](https://github.com/user-attachments/assets/251ea086-18df-4c6c-976b-de3dafe78585)

In simple admin per example i can do command with not the full name if the name is "banana" i cant do the command with "bana"

Solve this pls

**Comment by exkludera** [comment]
Userid is not supposed to be supported.
Not writing the full name is not supported either.

Use full name or steamid

`css_forcesay "full name" "message"`

**Comment by rodopoulos1** [comment]
why not? impossible fullname, exists some names that is other languge bro, arabic, china, we cant do this, yes u can change that when i type the initial frome name or something will took the player and read him name and yes works, will ask other people to doo this but tks
